[package]
name = "clean_zip"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[lib]
crate-type = ["cdylib", "rlib"]