[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "wxPython==4.1.1",  # Specify a version with pre-built wheels available
    "PySimpleGUIWx",
    "pyinstaller"
]
