name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Only macOS and Windows
        include:
          - os: macos-latest
            platform: macos
            extension: '.app'
          - os: windows-latest
            platform: windows
            extension: '.exe'
    continue-on-error: true  # Continue even if the platform-specific job fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Ensure Python 3.9 is used

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wxPython PySimpleGUIWx pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed delete_media_from_zip.py
        env:
          WXWIN: ${{ github.workspace }}  # Fix for wxPython on Windows

      - name: Verify build output (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          ls -al dist/

      - name: Verify build output (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Get-ChildItem dist

      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: delete_media_from_zip_${{ matrix.platform }}
          path: dist/delete_media_from_zip${{ matrix.extension }}
        if: success()  # Only upload if the build was successful

  create-release:
    name: Create GitHub Release
    needs: build-and-test
    runs-on: ubuntu-latest  # The release creation can still run on ubuntu-latest
    steps:
      - name: Download build artifacts for macOS
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: delete_media_from_zip_macos
          path: builds/macos/

      - name: Download build artifacts for Windows
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: delete_media_from_zip_windows
          path: builds/windows/

      - name: Create Release
        if: always()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Use the actual tag name
          name: Release ${{ github.ref_name }}  # Name the release after the tag
          body: |
            ## Changelog
            - Auto-generated release for ${{ github.ref_name }}

            ### Assets
            - Windows (.exe)
            - macOS (.app)
          files: |
            builds/windows/delete_media_from_zip.exe
            builds/macos/delete_media_from_zip.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
