name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.9]  # Supported Python versions
        include:
          - os: ubuntu-latest
            platform: linux
            extension: ''
          - os: macos-latest
            platform: macos
            extension: '.app'
          - os: windows-latest
            platform: windows
            extension: '.exe'



    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libjpeg-dev \
            libtiff-dev \
            libsdl1.2-dev \
            libnotify-dev \
            freeglut3-dev \
            libsm-dev \
            libgtk2.0-dev \
            libgtk-3-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wxPython PySimpleGUIWx pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed delete_media_from_zip.py
        env:
          WXWIN: ${{ github.workspace }}  # Fix for wxPython on Windows

      - name: Verify build output
        run: |
          ls -al dist/

      - name: Test the built executable
        run: |
          ./dist/delete_media_from_zip${{ matrix.extension }} --help
        continue-on-error: true  # Allows workflow to continue even if test fails

      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: delete_media_from_zip_${{ matrix.platform }}
          path: dist/delete_media_from_zip${{ matrix.extension }}

  create-release:
    name: Create GitHub Release
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: delete_media_from_zip_linux
          path: builds/
      - uses: actions/download-artifact@v3
        with:
          name: delete_media_from_zip_macos
          path: builds/
      - uses: actions/download-artifact@v3
        with:
          name: delete_media_from_zip_windows
          path: builds/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            ## Changelog
            - Auto-generated release for ${{ github.ref }}

            ### Assets
            - Windows (.exe)
            - macOS (.app)
            - Linux (binary)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          assets: |
            builds/delete_media_from_zip_windows.exe
            builds/delete_media_from_zip_macos
            builds/delete_media_from_zip_linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
